
//<developer>
//    <name>linapex 曹一峰</name>
//    <email>linapex@163.com</email>
//    <wx>superexc</wx>
//    <qqgroup>128148617</qqgroup>
//    <url>https://jsq.ink</url>
//    <role>pku engineer</role>
//    <date>2019-03-16 19:40:10</date>
//</624456013562515456>

//Code generated by mockery v1.0.0. 不要编辑。
package mocks

import mock "github.com/stretchr/testify/mock"
import validation "github.com/hyperledger/fabric/core/handlers/validation/api/identities"

//IdentityDeserializer是IdentityDeserializer类型的自动生成的模拟类型
type IdentityDeserializer struct {
	mock.Mock
}

//DeserializeIDentity提供了一个具有给定字段的模拟函数：SerializeIDentity
func (_m *IdentityDeserializer) DeserializeIdentity(serializedIdentity []byte) (validation.Identity, error) {
	ret := _m.Called(serializedIdentity)

	var r0 validation.Identity
	if rf, ok := ret.Get(0).(func([]byte) validation.Identity); ok {
		r0 = rf(serializedIdentity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validation.Identity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(serializedIdentity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

