
//<developer>
//    <name>linapex 曹一峰</name>
//    <email>linapex@163.com</email>
//    <wx>superexc</wx>
//    <qqgroup>128148617</qqgroup>
//    <url>https://jsq.ink</url>
//    <role>pku engineer</role>
//    <date>2019-03-16 19:40:06</date>
//</624455998467215360>

//Code generated by mockery v1.0.0. 不要编辑。
package mocks

import mock "github.com/stretchr/testify/mock"
import txvalidator "github.com/hyperledger/fabric/core/committer/txvalidator"
import validation "github.com/hyperledger/fabric/core/handlers/validation/api"

//pluginmapper是为pluginmapper类型自动生成的模拟类型
type PluginMapper struct {
	mock.Mock
}

//PlugInfactoryByName提供了一个具有给定字段的模拟函数：name
func (_m *PluginMapper) PluginFactoryByName(name txvalidator.PluginName) validation.PluginFactory {
	ret := _m.Called(name)

	var r0 validation.PluginFactory
	if rf, ok := ret.Get(0).(func(txvalidator.PluginName) validation.PluginFactory); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validation.PluginFactory)
		}
	}

	return r0
}

