
//<developer>
//    <name>linapex 曹一峰</name>
//    <email>linapex@163.com</email>
//    <wx>superexc</wx>
//    <qqgroup>128148617</qqgroup>
//    <url>https://jsq.ink</url>
//    <role>pku engineer</role>
//    <date>2019-03-16 19:40:06</date>
//</624455998408495104>

//Code generated by mockery v1.0.0. 不要编辑。
package mocks

import mock "github.com/stretchr/testify/mock"
import validation "github.com/hyperledger/fabric/core/handlers/validation/api"

//PlugInfectory是PlugInfectory类型的自动生成的模拟类型
type PluginFactory struct {
	mock.Mock
}

//new为给定字段提供模拟函数：
func (_m *PluginFactory) New() validation.Plugin {
	ret := _m.Called()

	var r0 validation.Plugin
	if rf, ok := ret.Get(0).(func() validation.Plugin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validation.Plugin)
		}
	}

	return r0
}

