
//<developer>
//    <name>linapex 曹一峰</name>
//    <email>linapex@163.com</email>
//    <wx>superexc</wx>
//    <qqgroup>128148617</qqgroup>
//    <url>https://jsq.ink</url>
//    <role>pku engineer</role>
//    <date>2019-03-16 19:40:23</date>
//</624456069363535872>

//Code generated by mockery v1.0.0. 不要编辑。
package mocks

import api "github.com/hyperledger/fabric/gossip/api"
import mock "github.com/stretchr/testify/mock"

//SecurityAdvisor是SecurityAdvisor类型的自动生成的模拟类型
type SecurityAdvisor struct {
	mock.Mock
}

//orgbypeerIdentity提供了一个具有给定字段的模拟函数：a0
func (_m *SecurityAdvisor) OrgByPeerIdentity(_a0 api.PeerIdentityType) api.OrgIdentityType {
	ret := _m.Called(_a0)

	var r0 api.OrgIdentityType
	if rf, ok := ret.Get(0).(func(api.PeerIdentityType) api.OrgIdentityType); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.OrgIdentityType)
		}
	}

	return r0
}

