
//<developer>
//    <name>linapex 曹一峰</name>
//    <email>linapex@163.com</email>
//    <wx>superexc</wx>
//    <qqgroup>128148617</qqgroup>
//    <url>https://jsq.ink</url>
//    <role>pku engineer</role>
//    <date>2019-03-16 19:40:30</date>
//</624456098547503104>

//Code generated by mockery v1.0.0. 不要编辑。

package mocks

import mock "github.com/stretchr/testify/mock"
import multichannel "github.com/hyperledger/fabric/orderer/common/multichannel"

//chainegetter是为chainegetter类型自动生成的模拟类型
type ChainGetter struct {
	mock.Mock
}

//getchain提供具有给定字段的模拟函数：chainID
func (_m *ChainGetter) GetChain(chainID string) *multichannel.ChainSupport {
	ret := _m.Called(chainID)

	var r0 *multichannel.ChainSupport
	if rf, ok := ret.Get(0).(func(string) *multichannel.ChainSupport); ok {
		r0 = rf(chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*multichannel.ChainSupport)
		}
	}

	return r0
}

