
//<developer>
//    <name>linapex 曹一峰</name>
//    <email>linapex@163.com</email>
//    <wx>superexc</wx>
//    <qqgroup>128148617</qqgroup>
//    <url>https://jsq.ink</url>
//    <role>pku engineer</role>
//    <date>2019-03-16 19:40:30</date>
//</624456098635583488>

//Code generated by mockery v1.0.0. 不要编辑。

package mocks

import cluster "github.com/hyperledger/fabric/orderer/common/cluster"

import mock "github.com/stretchr/testify/mock"

//配置器是为配置器类型自动生成的模拟类型
type Configurator struct {
	mock.Mock
}

//configure提供了一个具有给定字段的模拟函数：channel、newnodes
func (_m *Configurator) Configure(channel string, newNodes []cluster.RemoteNode) {
	_m.Called(channel, newNodes)
}

