
//<developer>
//    <name>linapex 曹一峰</name>
//    <email>linapex@163.com</email>
//    <wx>superexc</wx>
//    <qqgroup>128148617</qqgroup>
//    <url>https://jsq.ink</url>
//    <role>pku engineer</role>
//    <date>2019-03-16 19:40:30</date>
//</624456099034042368>

//Code generated by mockery v1.0.0. 不要编辑。

package mocks

import etcdraft "github.com/hyperledger/fabric/orderer/consensus/etcdraft"
import mock "github.com/stretchr/testify/mock"

//Receivergetter是为Receivergetter类型自动生成的模拟类型
type ReceiverGetter struct {
	mock.Mock
}

//ReceiverByChain提供了一个具有给定字段的模拟函数：channelID
func (_m *ReceiverGetter) ReceiverByChain(channelID string) etcdraft.MessageReceiver {
	ret := _m.Called(channelID)

	var r0 etcdraft.MessageReceiver
	if rf, ok := ret.Get(0).(func(string) etcdraft.MessageReceiver); ok {
		r0 = rf(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(etcdraft.MessageReceiver)
		}
	}

	return r0
}

